[package]
name = "wic"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = "0.32.5"
ldk-node = "0.5.0"
lightning = { git = "https://github.com/elnosh/rust-lightning.git", rev = "b65b6d2"}
rand = "0.8.5"
